name: mc_jsi
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  get_it: ^1.0.3+2
  provider: ^3.1.0
  fluttertoast: ^3.1.3
  date_format: ^1.0.8
  flutter_time_picker_spinner: ^1.0.6
  flutter_rounded_date_picker: ^0.2.3
  sailor: ^0.6.0
  sqflite: ^1.1.8
  path_provider: any
  numberpicker: ^1.1.0
  badges: ^1.1.0
  rflutter_alert: ^1.0.2
  flutter_calendar_carousel: ^1.4.10
  flutter_image_compress: ^0.6.3
  image_picker: ^0.6.1
  image: ^2.1.4
  easy_google_maps: ^1.0.0+2
  flutter_cupertino_date_picker: ^1.0.12
  google_sign_in: ^4.0.11
#  video_player: ^0.10.3+3




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - assets/
